### ISSUE TITLE
Wrapped parameters empty when JSON body sent to API

### ISSUE THREAD

**Issue by cutalion** [madebyhiro/codem-schedule#28]
When I try to create a job via API, I get validation error saying all attributes are missing.

```
$ curl -X POST -H "Content-Type: application/json" -d '{"input": "/tmp/foo.flv", "output": "/tmp/bar.mp4", "preset": "720_MP4"}' http://localhost:4000/api/jobs.json

{"errors":{"source_file":["can't be blank"],"destination_file":["can't be blank"],"preset_id":["can't be blank"]}}
```
Here is a log for this request.

```
I, [2014-08-13T19:35:25.166434 #4194]  INFO -- : Processing by Api::JobsController#create as JSON
I, [2014-08-13T19:35:25.166598 #4194]  INFO -- :   Parameters: {"input"=>"/tmp/foo.flv", "output"=>"/tmp/bar.mp4", "preset"=>"720_MP4", "job"=>{}}
```

There is an empty `job` parameter added by `wrap_parameters` feature in `rails` I guess.

Unfortunately method [`Job.from_api`](https://github.com/madebyhiro/codem-schedule/blob/master/app/models/job.rb#L35) will use this empty hash.

**Comment by bartzon** [comment]
Currently working on a rewrite, in which this issue will not occur anymore.
