### ISSUE TITLE
Scheduler cannot handle a large amount of scheduled jobs without slowing down

### ISSUE THREAD

**Issue by tieleman** [madebyhiro/codem-schedule#35]
The way the schedule endpoint works it breaks down when you have large amounts of jobs scheduled (10k+). The `Schedule.run!` method retrieves *all* scheduled jobs from the database and tries to schedule them regardless of how many slots are actually available.

Proposed change is to split into two phases: updating the jobs that are `Processing` or `OnHold`. After that scheduling jobs, but only retrieve as many from the database as there are slots available.

```ruby
def run!
  jobs = to_be_updated_jobs
  jobs.each do |job|
    job.with_lock(true) do
      update_job(job)
    end
  end

  size = jobs.size
  
  jobs = to_be_scheduled_jobs
  jobs.each do |job|
    job.with_lock(true) do
      schedule_job(job)
    end
  end
  
  size + jobs.size
end

def to_be_updated_jobs
  Job.where(state: [Job::Processing, Job::OnHold])
end

def to_be_scheduled_jobs
  Job.where(state: Job::Scheduled).order('created_at').limit(available_slots)
end
```

(this can be written more cleanly though)

**Comment by tieleman** [comment]
👍🏻🎉

**Comment by deedos** [comment]
Would be possible to set manually the maximum number of processing jobs ? I ask because when all slots are being used ffmpeg tends to reach 100% and the codem_schedule itself becomes unresponsevely.
thanks

**Comment by tieleman** [comment]
In the config of codem-transcode you can specify the maximum number of slots available. That in combination with setting a lower amount of threads in the ffmpeg options should result in less CPU starvation.

Also, you can run codem-schedule and codem-transcode on separate machines to avoid this.
