### ISSUE TITLE
Preset not supporting HLS 

### ISSUE THREAD

**Issue by bibbychan** [madebyhiro/codem-schedule#37]
I am Happy and thank to this project .

since the ffmpeg support HLS  , but codem-schedule cant apply with preset to transcode HLS format .

workaround for HLS ,each file to transcode HLS have to create it's own preset to fill in the ffmpeg option.

**Comment by bartzon** [comment]
Check out the (experimental!) HLS branch: https://github.com/madebyhiro/codem-schedule/tree/hls
